local NEW_RECIPES = {
    ["atts_saigafh"] = {
		["name"] = "Saiga-12 Flash Hider",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a Saiga-12 Flash Hider",
		["requirements"] = {["scrapmetal"] = 6, ["advancedtools"] = 1},
		["results"] = {["saigafh"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_heavybarrel"] = {
		["name"] = "",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a Heavy Barrel",
		["requirements"] = {["scrapmetal"] = 9, ["advancedtools"] = 1},
		["results"] = {["heavybarrel"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_pbs5"] = {
		["name"] = "PBS-5",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a PBS-5 Suppressor",
		["requirements"] = {["scrapmetal"] = 12, ["advancedtools"] = 1},
		["results"] = {["pbs5"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
		
	},
	["atts_pbs1"] = {
		["name"] = "PBS-1",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a PBS-1 Suppressor",
		["requirements"] = {["scrapmetal"] = 12, ["advancedtools"] = 1},
		["results"] = {["pbs1"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_suppnato"] = {
		["name"] = "NATO Suppressor",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a NATO Suppressor",
		["requirements"] = {["scrapmetal"] = 12, ["advancedtools"] = 1},
		["results"] = {["suppnato"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_supp12"] = {
		["name"] = "12 Gauge Suppressor",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a 12 Gauge Suppressor",
		["requirements"] = {["scrapmetal"] = 13, ["advancedtools"] = 1},
		["results"] = {["supp12"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_speedloader"] = {
		["name"] = "Speed Loader",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a Speed Loader",
		["requirements"] = {["scrapmetal"] = 4, ["advancedtools"] = 1},
		["results"] = {["speedloader"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_saigadrum"] = {
		["name"] = "Saiga-12 Drum Magazine",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a Saiga-12 Drum Magazine",
		["requirements"] = {["scrapmetal"] = 6, ["advancedtools"] = 1},
		["results"] = {["saigadrum"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_light"] = {
		["name"] = "Flashlight",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a Flashlight",
		["requirements"] = {["scrapmetal"] = 4, ["wire"] = 3, ["electronics"] = 3, ["flux"] = 2, ["solder"] = 1, ["advancedtools"] = 1},
		["results"] = {["light"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_laser"] = {
		["name"] = "Laser",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a barrel-mounted laser.",
		["requirements"] = {["scrapmetal"] = 4, ["wire"] = 3, ["electronics"] = 4, ["flux"] = 2, ["solder"] = 2, ["advancedtools"] = 1},
		["results"] = {["laser"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_m6x"] = {
		["name"] = "M6X",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a M6X",
		["requirements"] = {["scrapmetal"] = 6, ["wire"] = 5, ["electronics"] = 5, ["flux"] = 3, ["solder"] = 2, ["advancedtools"] = 1},
		["results"] = {["m6x"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_anpeq"] = {
		["name"] = "AN/PEQ-15",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a AN/PEQ-15",
		["requirements"] = {["scrapmetal"] = 6, ["wire"] = 4, ["electronics"] = 5, ["flux"] = 3, ["solder"] = 2, ["advancedtools"] = 1},
		["results"] = {["anpeq"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_vertgrip"] = {
		["name"] = "Vertical Grip",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a Vertical Grip",
		["requirements"] = {["scrapmetal"] = 7, ["advancedtools"] = 1},
		["results"] = {["vertgrip"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_bipod"] = {
		["name"] = "Bipod",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["scrapmetal"] = 14, ["advancedtools"] = 1},
		["results"] = {["bipod"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_gp25"] = {
		["name"] = "GP-25",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a GP-25",
		["requirements"] = {["scrapmetal"] = 20, ["advancedinternals"] = 1, ["advancedtools"] = 1},
		["results"] = {["gp25"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_attm203"] = {
		["name"] = "M203",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a M203",
		["requirements"] = {["scrapmetal"] = 20, ["advancedinternals"] = 1, ["advancedtools"] = 1},
		["results"] = {["attm203"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_kobra"] = {
		["name"] = "Kobra Red Dot Sight",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a Kobra Red Dot Sight",
		["requirements"] = {["scrapmetal"] = 7, ["wire"] = 3, ["electronics"] = 3, ["flux"] = 2, ["solder"] = 1, ["advancedtools"] = 1},
		["results"] = {["kobra"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_aimpoint"] = {
		["name"] = "Aimpoint Red Dot Sight",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a Aimpoint Red Dot Sight",
		["requirements"] = {["scrapmetal"] = 5, ["wire"] = 3, ["electronics"] = 4, ["flux"] = 2, ["solder"] = 2, ["advancedtools"] = 1},
		["results"] = {["aimpoint"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_eotech"] = {
		["name"] = "Eotech Holosight",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a Eotech Holosight",
		["requirements"] = {["scrapmetal"] = 10, ["wire"] = 4, ["electronics"] = 6, ["flux"] = 3, ["solder"] = 3, ["advancedtools"] = 1},
		["results"] = {["eotech"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_microt1"] = {
		["name"] = "Micro T-1 Red Dot Sight",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a Micro T-1 Red Dot Sight",
		["requirements"] = {["scrapmetal"] = 7, ["wire"] = 4, ["electronics"] = 5, ["flux"] = 3, ["solder"] = 2, ["advancedtools"] = 1},
		["results"] = {["microt1"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_compm4s"] = {
		["name"] = "Aimpoint CompM4S",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a Aimpoint CompM4S",
		["requirements"] = {["scrapmetal"] = 7, ["wire"] = 4, ["electronics"] = 5, ["flux"] = 3, ["solder"] = 2, ["advancedtools"] = 1},
		["results"] = {["compm4s"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_eotechxps"] = {
		["name"] = "Eotech XPS2",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a Eotech XPS2",
		["requirements"] = {["scrapmetal"] = 11, ["wire"] = 6, ["electronics"] = 6, ["flux"] = 3, ["solder"] = 3, ["advancedtools"] = 1},
		["results"] = {["eotechxps"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_cmore"] = {
		["name"] = "C-More Red Dot Sight",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a C-More Red Dot Sight",
		["requirements"] = {["scrapmetal"] = 10, ["wire"] = 6, ["electronics"] = 5, ["flux"] = 3, ["solder"] = 2, ["advancedtools"] = 1},
		["results"] = {["cmore"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_barska"] = {
		["name"] = "Barksa Electro Sight",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a Barksa Electro Sight",
		["requirements"] = {["scrapmetal"] = 10, ["wire"] = 6, ["electronics"] = 5, ["flux"] = 3, ["solder"] = 2, ["advancedtools"] = 1},
		["results"] = {["barska"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_po4"] = {
		["name"] = "PO 4x24 Scope",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a PO 4x24 Scope",
		["requirements"] = {["scrapmetal"] = 14, ["wire"] = 2, ["electronics"] = 2, ["flux"] = 1, ["solder"] = 1, ["advancedtools"] = 1},
		["results"] = {["po4"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_acog"] = {
		["name"] = "ACOG 4x32 Scope",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a ACOG 4x32 Scope",
		["requirements"] = {["scrapmetal"] = 13, ["wire"] = 6, ["electronics"] = 6, ["flux"] = 3, ["solder"] = 3, ["advancedtools"] = 1},
		["results"] = {["acog"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_elcan"] = {
		["name"] = "Elcan Optical Scope",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a Elcan Optical Scope",
		["requirements"] = {["scrapmetal"] = 17, ["wire"] = 2, ["electronics"] = 2, ["flux"] = 1, ["solder"] = 1, ["advancedtools"] = 1},
		["results"] = {["elcan"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_leupold"] = {
		["name"] = "Leupold Scope",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["scrapmetal"] = 17, ["wire"] = 2, ["electronics"] = 2, ["flux"] = 1, ["solder"] = 1, ["advancedtools"] = 1},
		["results"] = {["leupold"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_m40scope"] = {
		["name"] = "M40A1 Scope",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a M40A1 Scope",
		["requirements"] = {["scrapmetal"] = 18, ["wire"] = 2, ["electronics"] = 2, ["flux"] = 1, ["solder"] = 1, ["advancedtools"] = 1},
		["results"] = {["m40scope"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["atts_supppistol"] = {
		["name"] = "Pistol Suppressor",
		["model"] = "models/Items/BoxSRounds.mdl",
		["desc"] = "Create a Pistol Suppressor",
		["requirements"] = {["scrapmetal"] = 7, ["advancedtools"] = 1},
		["results"] = {["supppistol"] = 1},
		["category"] = "Attachments",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
}

for k, v in pairs(NEW_RECIPES) do
	PLUGIN:AddRecipe(v.name, v.model, v.desc, v.requirements, v.results, k, v.skill or nil, v.blueprint or nil, v.guns or nil, v.entity or nil, v.category or "Miscellaneous", v.crafttable or nil)
end