local NEW_RECIPES = {
    ["ammo_9x18"] = {
		["name"] = "9x18mm",
		["model"] = "models/kek1ch/ammo_9x18_fmj.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 1, ["scrapmetal"] = 1, ["brass"] = 1, ["basictools"] = 1},
		["results"] = {["9x18"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_9x19"] = {
		["name"] = "9x19mm",
		["model"] = "models/kek1ch/ammo_9x19_fmj.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 1, ["scrapmetal"] = 1, ["brass"] = 1, ["basictools"] = 1},
		["results"] = {["9x19"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_9x21"] = {
		["name"] = "9x21mm",
		["model"] = "models/kek1ch/ammo_9x19_pbp.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 2, ["scrapmetal"] = 2, ["brass"] = 2, ["basictools"] = 1},
		["results"] = {["9x21"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_38"] = {
		["name"] = ".38 Special",
		["model"] = "models/Items/357ammo.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 1, ["scrapmetal"] = 1, ["brass"] = 1, ["basictools"] = 1},
		["results"] = {["38"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_762x25"] = {
		["name"] = "7.62x25mm",
		["model"] = "models/kek1ch/ammo_762x25_p.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 2, ["scrapmetal"] = 3, ["brass"] = 2, ["basictools"] = 1},
		["results"] = {["762x25"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_57"] = {
		["name"] = "5.7x28mm",
		["model"] = "models/kek1ch/ammo_762x25_ps.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 2, ["scrapmetal"] = 3, ["brass"] = 2, ["basictools"] = 1},
		["results"] = {["57x28"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_45"] = {
		["name"] = ".45 ACP",
		["model"] = "models/kek1ch/ammo_1143x23_fmj.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 3, ["scrapmetal"] = 4, ["brass"] = 3, ["basictools"] = 1},
		["results"] = {["45acp"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_357"] = {
		["name"] = ".357 Magnum",
		["model"] = "models/Items/357ammo.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 3, ["scrapmetal"] = 4, ["brass"] = 3, ["basictools"] = 1},
		["results"] = {["357"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_50"] = {
		["name"] = ".50 AE",
		["model"] = "models/kek1ch/ammo_50_ae.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 4, ["scrapmetal"] = 6, ["brass"] = 4, ["basictools"] = 1},
		["results"] = {["50ae"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_12x70bird"] = {
		["name"] = "12 Gauge Birdshot",
		["model"] = "models/kek1ch/ammo_12x70_buck.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 5, ["scrapmetal"] = 7, ["brass"] = 5, ["basictools"] = 1},
		["results"] = {["12gaugebd"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_12x70"] = {
		["name"] = "12 Gauge Buckshot",
		["model"] = "models/kek1ch/ammo_12x70_buck.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 5, ["scrapmetal"] = 7, ["brass"] = 5, ["basictools"] = 1},
		["results"] = {["12gauge"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_12x70slug"] = {
		["name"] = "12 Gauge Slug",
		["model"] = "models/kek1ch/ammo_12x70_buck.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 6, ["scrapmetal"] = 9, ["brass"] = 6, ["basictools"] = 1},
		["results"] = {["12gaugesg"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_12x70tri"] = {
		["name"] = "12 Gauge Trishot",
		["model"] = "models/kek1ch/ammo_12x70_buck.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 5, ["scrapmetal"] = 7, ["brass"] = 5, ["basictools"] = 1},
		["results"] = {["12gaugetr"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_762x39"] = {
		["name"] = "7.62x39mm",
		["model"] = "models/kek1ch/ammo_762x39_ap.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 5, ["scrapmetal"] = 7, ["brass"] = 5, ["basictools"] = 1},
		["results"] = {["762x39"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_545x39"] = {
		["name"] = "5.45x39mm",
		["model"] = "models/kek1ch/ammo_545x39_fmj.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 5, ["scrapmetal"] = 7, ["brass"] = 5, ["basictools"] = 1},
		["results"] = {["545x39"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_556x45"] = {
		["name"] = "5.56x45mm",
		["model"] = "models/kek1ch/ammo_556x45_ss190.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 5, ["scrapmetal"] = 7, ["brass"] = 5, ["basictools"] = 1},
		["results"] = {["556x45"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_9x39"] = {
		["name"] = "9x39mm",
		["model"] = "models/kek1ch/ammo_9x39_pab9.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 6, ["scrapmetal"] = 8, ["brass"] = 6, ["basictools"] = 1},
		["results"] = {["9x39"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_762x51"] = {
		["name"] = "7.62x51mm",
		["model"] = "models/kek1ch/ammo_762x54_7h14.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 7, ["scrapmetal"] = 9, ["brass"] = 7, ["basictools"] = 1},
		["results"] = {["762x51"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_762x54"] = {
		["name"] = "7.62x54mmR",
		["model"] = "models/kek1ch/ammo_762x54_7h1.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 7, ["scrapmetal"] = 9, ["brass"] = 7, ["basictools"] = 1},
		["results"] = {["762x54"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_23"] = {
		["name"] = "23mm Buckshot",
		["model"] = "models/kek1ch/ammo_12x76_zhekan.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 9, ["scrapmetal"] = 12, ["brass"] = 9, ["basictools"] = 1},
		["results"] = {["23"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_762x51belt"] = {
		["name"] = "7.62x51mm Belt",
		["model"] = "models/kek1ch/ammo_pkm.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 35, ["scrapmetal"] = 45, ["brass"] = 35, ["basictools"] = 1},
		["results"] = {["762x51belt"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_762x54belt"] = {
		["name"] = "7.62x54mm Belt",
		["model"] = "models/kek1ch/ammo_pkm.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["gunpowder"] = 35, ["scrapmetal"] = 45, ["brass"] = 35, ["basictools"] = 1},
		["results"] = {["762x54belt"] = 1},
		["category"] = "Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["ammo_molotov"] = {
		["name"] = "Molotov Cocktail",
		["model"] = "models/weapons/ethereal/w_molotov.mdl",
		["desc"] = "Create a ",
		["requirements"] = {["alcohol"] = 2, ["cloth"] = 2, ["basictools"] = 1},
		["results"] = {["molotov"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
}

for k, v in pairs(NEW_RECIPES) do
	PLUGIN:AddRecipe(v.name, v.model, v.desc, v.requirements, v.results, k, v.skill or nil, v.blueprint or nil, v.guns or nil, v.entity or nil, v.category or "Miscellaneous", v.crafttable or nil)
end