local NEW_RECIPES = {
    ["guns_aks74u"] = {
		["name"] = "AKS-74u",
		["model"] = "models/weapons/ethereal/item_aks74u.mdl",
		["desc"] = "Put together an AKS-74U",
		["requirements"] = {["basicriflebody"] = 1, ["basicauto"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 15, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["aks74u"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_m16a4"] = {
		["name"] = "M16A4",
		["model"] = "models/weapons/ethereal/w_m16.mdl",
		["desc"] = "Put together an M16A4",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 20, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["m16a4"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_aks74uz"] = {
		["name"] = "AKS-74u Zenith",
		["model"] = "models/weapons/ethereal/w_aks74uz.mdl",
		["desc"] = "Put together an AKS-74U Zenith",
		["requirements"] = {["basicriflebody"] = 1, ["basicauto"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 20, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["aks74uz"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_akm"] = {
		["name"] = "AKM",
		["model"] = "models/weapons/ethereal/item_akm.mdl",
		["desc"] = "Put together an AKM",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 25, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["akm"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_vz58"] = {
		["name"] = "VZ-58",
		["model"] = "models/weapons/ethereal/w_vz58.mdl",
		["desc"] = "Put together an VZ-58",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 20, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["vz58"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_ak74"] = {
		["name"] = "AK-74",
		["model"] = "models/weapons/ethereal/item_ak74.mdl",
		["desc"] = "Put together an AK-74",
		["requirements"] = {["basicriflebody"] = 1, ["basicauto"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 25, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["ak74"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_l85a2"] = {
		["name"] = "L85A2",
		["model"] = "models/weapons/ethereal/w_l85a2.mdl",
		["desc"] = "Put together a L85A2",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 30, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["l85a2"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_famasf1"] = {
		["name"] = "Famas F1",
		["model"] = "models/weapons/ethereal/w_famasf1.mdl",
		["desc"] = "Put together a Famas F1",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 30, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["famasf1"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_m4a1"] = {
		["name"] = "M4A1",
		["model"] = "models/weapons/ethereal/w_m4a1.mdl",
		["desc"] = "Put together a M4A1",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 30, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["m4a1"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_ak74z"] = {
		["name"] = "AK-74 Zenith",
		["model"] = "models/weapons/ethereal/w_ak74z.mdl",
		["desc"] = "Put together an AK-74 Zenith",
		["requirements"] = {["basicriflebody"] = 1, ["basicauto"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 30, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["ak74z"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_aks74n"] = {
		["name"] = "AKS-74N",
		["model"] = "models/weapons/ethereal/item_ak742.mdl",
		["desc"] = "Put together an AKS-74N",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 30, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["aks74n"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_g36c"] = {
		["name"] = "G36c",
		["model"] = "models/weapons/ethereal/w_g36c.mdl",
		["desc"] = "Put together a G36c",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 35, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["g36c"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_akmconc"] = {
		["name"] = "Concern AKM",
		["model"] = "models/weapons/ethereal/w_akmconc.mdl",
		["desc"] = "Put together a Kalashnikov Concern AKM",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 35, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["akmconc"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_ak105"] = {
		["name"] = "AK-105",
		["model"] = "models/weapons/ethereal/w_f_ak105.mdl",
		["desc"] = "Put together an AK-105",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 35, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["ak105"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_ak103"] = {
		["name"] = "AK-103",
		["model"] = "models/weapons/ethereal/w_f_ak103.mdl",
		["desc"] = "Put together an AK-103",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 40, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["ak103"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_lr300"] = {
		["name"] = "LR-300",
		["model"] = "models/weapons/ethereal/w_lr300.mdl",
		["desc"] = "Put together a LR-300",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 40, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["lr300"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_sg552"] = {
		["name"] = "SG-552",
		["model"] = "models/weapons/ethereal/sg552/w_sg552.mdl",
		["desc"] = "Put together a SG-552",
		["requirements"] = {["basicriflebody"] = 1, ["basicauto"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 40, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["sg552"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_aug"] = {
		["name"] = "AUG A3",
		["model"] = "models/weapons/ethereal/w_aug.mdl",
		["desc"] = "Put together an AUG A3",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 40, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["aug"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_hk416"] = {
		["name"] = "HK416",
		["model"] = "models/weapons/ethereal/w_hk416.mdl",
		["desc"] = "Put together a HK416",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 40, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["hk416"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_abakan"] = {
		["name"] = "AN-94 Abakan",
		["model"] = "models/weapons/ethereal/w_abakan.mdl",
		["desc"] = "Put together an AN-94 Abakan",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 40, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["abakan"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_sg551"] = {
		["name"] = "SG-551",
		["model"] = "models/weapons/ethereal/w_sg5511.mdl",
		["desc"] = "Put together a SG-551",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 45, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["sg551"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_aek971"] = {
		["name"] = "AEK-971",
		["model"] = "models/weapons/ethereal/w_aek971.mdl",
		["desc"] = "Put together a SG-551",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 45, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["aek971"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_mk18"] = {
		["name"] = "MK18",
		["model"] = "models/weapons/ethereal/w_mk18.mdl",
		["desc"] = "Put together a MK18",
		["requirements"] = {["basicriflebody"] = 1, ["basicauto"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 45, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["mk18"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_galil"] = {
		["name"] = "Galil",
		["model"] = "models/weapons/ethereal/w_galil.mdl",
		["desc"] = "Put together a Galil",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 45, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["galil"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_groza762"] = {
		["name"] = "Groza",
		["model"] = "models/weapons/ethereal/item_groza1.mdl",
		["desc"] = "Put together a Groza",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 45, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["groza762"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_cz805"] = {
		["name"] = "CZ-805",
		["model"] = "models/weapons/ethereal/w_cz805.mdl",
		["desc"] = "Put together a CZ-805",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 45, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["cz805"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_acr556"] = {
		["name"] = "ACR",
		["model"] = "models/weapons/ethereal/w_acr.mdl",
		["desc"] = "Put together an ACR",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 50, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["acr"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_akalfa"] = {
		["name"] = "AK Alfa",
		["model"] = "models/weapons/ethereal/w_alfa.mdl",
		["desc"] = "Put together an AK Alfa",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 55, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["akalfa"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_scarl"] = {
		["name"] = "SCAR-L",
		["model"] = "models/weapons/ethereal/w_sca.mdl",
		["desc"] = "Put together a SCAR-L",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 55, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["scarl"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_fnf2000"] = {
		["name"] = "FN F2000",
		["model"] = "models/weapons/ethereal/w_fnf2000.mdl",
		["desc"] = "Put together a FN F2000",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 60, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["fnf2000"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_pernach"] = {
		["name"] = "OTS-33 Pernach",
		["model"] = "models/weapons/ethereal/w_pernach.mdl",
		["desc"] = "Put together an OTS-33 Pernach",
		["requirements"] = {["basicsmgbody"] = 1, ["basicauto"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 5, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["pernach"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_pm9"] = {
		["name"] = "Minibea PM-9",
		["model"] = "models/weapons/ethereal/w_pm9.mdl",
		["desc"] = "Put together a Minibea PM-9",
		["requirements"] = {["basicsmgbody"] = 1, ["basicauto"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 7, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["pm9"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_mp5k"] = {
		["name"] = "MP5K",
		["model"] = "models/weapons/ethereal/w_mp5k.mdl",
		["desc"] = "Put together a MP5K",
		["requirements"] = {["basicsmgbody"] = 1, ["basicauto"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 8, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["mp5k"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_m4spec"] = {
		["name"] = "M4 Spectre",
		["model"] = "models/weapons/ethereal/w_m4spec.mdl",
		["desc"] = "Put together a M4 Spectre",
		["requirements"] = {["standardsmgbody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 8, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["m4spec"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_mac10"] = {
		["name"] = "Mac-10",
		["model"] = "models/weapons/ethereal/w_mac10.mdl",
		["desc"] = "Put together a Mac-10",
		["requirements"] = {["basicsmgbody"] = 1, ["basicauto"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 10, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["mac10"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_veresk"] = {
		["name"] = "SR-2 Veresk",
		["model"] = "models/weapons/ethereal/w_veresk.mdl",
		["desc"] = "Put together a SR-2 Veresk",
		["requirements"] = {["advancedsmgbody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 10, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["veresk"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_vityaz"] = {
		["name"] = "Vityaz",
		["model"] = "models/weapons/ethereal/w_vityaz.mdl",
		["desc"] = "Put together a Vityaz",
		["requirements"] = {["standardsmgbody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 12, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["vityaz"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_mp5a4"] = {
		["name"] = "MP5A4",
		["model"] = "models/weapons/ethereal/w_mp5a4.mdl",
		["desc"] = "Put together a MP5A4",
		["requirements"] = {["standardsmgbody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 15, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["mp5a4"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_ump45"] = {
		["name"] = "UMP-45",
		["model"] = "models/weapons/ethereal/w_ump45.mdl",
		["desc"] = "Put together an UMP-45",
		["requirements"] = {["advancedsmgbody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 17, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["ump45"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_uzi"] = {
		["name"] = "IMI Uzi",
		["model"] = "models/weapons/ethereal/w_uzi.mdl",
		["desc"] = "Put together an IMI Uzi",
		["requirements"] = {["standardsmgbody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 17, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["uzi"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_vector"] = {
		["name"] = "Kriss Vector",
		["model"] = "models/weapons/ethereal/w_vector.mdl",
		["desc"] = "Put together a Kriss Vector",
		["requirements"] = {["advancedsmgbody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 20, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["vector"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_scorpion"] = {
		["name"] = "CZ Scorpion EVO3",
		["model"] = "models/weapons/ethereal/w_scorpion.mdl",
		["desc"] = "Put together a CZ Scorpion EVO3",
		["requirements"] = {["advancedsmgbody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 25, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["scorpion"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_m10snub"] = {
		["name"] = "Snubnose SW M10",
		["model"] = "models/weapons/ethereal/w_m10.mdl",
		["desc"] = "Put together a Snubnose SW M10",
		["requirements"] = {["basicpistolbody"] = 1, ["basicsemi"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 2},
		["results"] = {["m10chrome"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_m10"] = {
		["name"] = "SW M10",
		["model"] = "models/weapons/ethereal/w_38rev.mdl",
		["desc"] = "Put together a SW M10",
		["requirements"] = {["basicpistolbody"] = 1, ["basicsemi"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 3},
		["results"] = {["m10"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_makarov"] = {
		["name"] = "Makarov",
		["model"] = "models/weapons/ethereal/w_makarov.mdl",
		["desc"] = "Put together a Makarov",
		["requirements"] = {["basicpistolbody"] = 1, ["basicsemi"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 3},
		["results"] = {["makarov"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_m9"] = {
		["name"] = "M9",
		["model"] = "models/weapons/ethereal/w_m9.mdl",
		["desc"] = "Put together a M9",
		["requirements"] = {["standardpistolbody"] = 1, ["standardsemi"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 4},
		["results"] = {["m9"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_m1911"] = {
		["name"] = "M1911",
		["model"] = "models/weapons/ethereal/w_1911.mdl",
		["desc"] = "Put together a M1911",
		["requirements"] = {["standardpistolbody"] = 1, ["standardsemi"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 4},
		["results"] = {["m1911"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_glock"] = {
		["name"] = "Glock",
		["model"] = "models/weapons/ethereal/w_glock.mdl",
		["desc"] = "Put together a Glock",
		["requirements"] = {["standardpistolbody"] = 1, ["standardsemi"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 4},
		["results"] = {["glock"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_tokarev"] = {
		["name"] = "Tokarev",
		["model"] = "models/weapons/ethereal/w_tokarev.mdl",
		["desc"] = "Put together a Tokarev",
		["requirements"] = {["standardpistolbody"] = 1, ["standardsemi"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 4},
		["results"] = {["tokarev"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_grach"] = {
		["name"] = "MP-443 Grach",
		["model"] = "models/weapons/ethereal/w_grach.mdl",
		["desc"] = "Put together a MP-443 Grach",
		["requirements"] = {["standardpistolbody"] = 1, ["standardsemi"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 5},
		["results"] = {["grach"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_m45"] = {
		["name"] = "M45",
		["model"] = "models/weapons/ethereal/w_m45.mdl",
		["desc"] = "Put together a M45",
		["requirements"] = {["advancedpistolbody"] = 1, ["advancedsemi"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 6, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["m45"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_usp45"] = {
		["name"] = "USP .45",
		["model"] = "models/weapons/ethereal/w_usp45.mdl",
		["desc"] = "Put together a USP .45",
		["requirements"] = {["advancedpistolbody"] = 1, ["advancedsemi"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 7, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["usp45"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_p226"] = {
		["name"] = "P226R",
		["model"] = "models/weapons/ethereal/w_p226.mdl",
		["desc"] = "Put together a P226R",
		["requirements"] = {["standardpistolbody"] = 1, ["basicsemi"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 7, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["p226"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_p99"] = {
		["name"] = "Walther P99",
		["model"] = "models/weapons/ethereal/w_p99.mdl",
		["desc"] = "Put together a Walther P99",
		["requirements"] = {["standardpistolbody"] = 1, ["standardsemi"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 8, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["p99"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_python"] = {
		["name"] = "Colt Python",
		["model"] = "models/weapons/ethereal/w_python.mdl",
		["desc"] = "Put together a Colt Python",
		["requirements"] = {["advancedpistolbody"] = 1, ["advancedsemi"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 10, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["p99"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_cz75"] = {
		["name"] = "CZ-75",
		["model"] = "models/weapons/ethereal/w_cz75.mdl",
		["desc"] = "Put together a CZ-75",
		["requirements"] = {["standardpistolbody"] = 1, ["standardsemi"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 10, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["cz75"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_fnp45"] = {
		["name"] = "FN FNP-45",
		["model"] = "models/weapons/ethereal/w_fnp.mdl",
		["desc"] = "Put together a FN FNP-45",
		["requirements"] = {["advancedpistolbody"] = 1, ["standardsemi"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 12, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["fnp"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_fiveseven"] = {
		["name"] = "FN Fiveseven",
		["model"] = "models/weapons/ethereal/w_fiveseven.mdl",
		["desc"] = "Put together a FN Fiveseven",
		["requirements"] = {["advancedpistolbody"] = 1, ["standardsemi"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 14, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["fiveseven"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_mr96"] = {
		["name"] = "MR-96",
		["model"] = "models/weapons/ethereal/w_mr96.mdl",
		["desc"] = "Put together a MR-96",
		["requirements"] = {["advancedpistolbody"] = 1, ["standardsemi"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 15, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["mr96"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_deagle"] = {
		["name"] = "Desert Eagle",
		["model"] = "models/weapons/ethereal/w_deagle.mdl",
		["desc"] = "Put together a Desert Eagle",
		["requirements"] = {["advancedpistolbody"] = 1, ["advancedsemi"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 20, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["deagle"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_m40a1"] = {
		["name"] = "M40A1",
		["model"] = "models/weapons/ethereal/w_m40.mdl",
		["desc"] = "Put together a M40A1",
		["requirements"] = {["standardriflebody"] = 1, ["standardbolt"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 20, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["m40a1"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_sks"] = {
		["name"] = "SKS",
		["model"] = "models/weapons/ethereal/w_sks.mdl",
		["desc"] = "Put together a SKS",
		["requirements"] = {["standardriflebody"] = 1, ["standardsemi"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 20, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["sks"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_mosin"] = {
		["name"] = "Mosin Nagant",
		["model"] = "models/weapons/ethereal/w_mosin.mdl",
		["desc"] = "Put together a Mosin Nagant",
		["requirements"] = {["standardriflebody"] = 1, ["standardbolt"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 20, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["mosin"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_saiga762"] = {
		["name"] = "Saiga 7.62",
		["model"] = "models/weapons/ethereal/w_saiga762.mdl",
		["desc"] = "Put together a Saiga 7.62",
		["requirements"] = {["standardriflebody"] = 1, ["standardsemi"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 25, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["saiga762"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_g3a3"] = {
		["name"] = "G3A3",
		["model"] = "models/weapons/ethereal/w_g3a3.mdl",
		["desc"] = "Put together a G3A3",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 30, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["g3a3"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_fnfal"] = {
		["name"] = "FN FAL",
		["model"] = "models/weapons/ethereal/w_fal.mdl",
		["desc"] = "Put together a FN FAL",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 30, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["fnfal"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_vss"] = {
		["name"] = "VSS Vintorez",
		["model"] = "models/weapons/ethereal/w_vss.mdl",
		["desc"] = "Put together a VSS Vintorez",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 35, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["vss"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_sv98b"] = {
		["name"] = "Black SV-98",
		["model"] = "models/weapons/ethereal/w_sv98b.mdl",
		["desc"] = "Put together a Black SV-98",
		["requirements"] = {["standardriflebody"] = 1, ["standardbolt"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 35, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["sv98b"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_asval"] = {
		["name"] = "AS Val",
		["model"] = "models/weapons/ethereal/w_asval.mdl",
		["desc"] = "Put together an AS Val",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 40, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["asval"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_svd"] = {
		["name"] = "SVD",
		["model"] = "models/weapons/ethereal/w_svd.mdl",
		["desc"] = "Put together a SVD",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedsemi"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 50, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["svd"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_sawedizh43"] = {
		["name"] = "Sawed Off TOZ-66",
		["model"] = "models/weapons/ethereal/w_sawnoff_db.mdl",
		["desc"] = "Put together a Sawed Off TOZ-66",
		["requirements"] = {["basicshotgunbody"] = 1, ["basicpump"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 4, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["toz66sawed"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_izh43"] = {
		["name"] = "TOZ-66",
		["model"] = "models/weapons/ethereal/w_doublebarrel.mdl",
		["desc"] = "Put together a TOZ-66",
		["requirements"] = {["basicshotgunbody"] = 1, ["basicpump"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 8, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["toz66"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_sawedithaca37"] = {
		["name"] = "Sawed Off Ithaca 37",
		["model"] = "models/weapons/ethereal/w_sawedithaca37.mdl",
		["desc"] = "Put together a Sawed Off Ithaca 37",
		["requirements"] = {["basicshotgunbody"] = 1, ["basicpump"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 12, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["sawedithaca37"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_ithaca37"] = {
		["name"] = "Ithaca 37",
		["model"] = "models/weapons/ethereal/w_ithaca37.mdl",
		["desc"] = "Put together an Ithaca 37",
		["requirements"] = {["standardshotgunbody"] = 1, ["standardpump"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 15, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["ithaca37"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_toz194"] = {
		["name"] = "TOZ-194",
		["model"] = "models/weapons/ethereal/w_toz.mdl",
		["desc"] = "Put together a TOZ-194",
		["requirements"] = {["basicshotgunbody"] = 1, ["basicpump"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 15, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["toz194"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_fort500"] = {
		["name"] = "Fort-500",
		["model"] = "models/weapons/ethereal/w_fort500.mdl",
		["desc"] = "Put together a Fort-500",
		["requirements"] = {["standardshotgunbody"] = 1, ["standardpump"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 15, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["fort500"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_mossberg88"] = {
		["name"] = "Chaser 13",
		["model"] = "models/weapons/ethereal/w_chaser13.mdl",
		["desc"] = "Put together a Chaser 13",
		["requirements"] = {["standardshotgunbody"] = 1, ["standardpump"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 18, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["chaser13"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_m590"] = {
		["name"] = "M590",
		["model"] = "models/weapons/ethereal/w_m590.mdl",
		["desc"] = "Put together a Mossberg M590",
		["requirements"] = {["standardshotgunbody"] = 1, ["standardpump"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 20, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["m590"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_spas12"] = {
		["name"] = "SPAS-12",
		["model"] = "models/weapons/ethereal/w_spas12.mdl",
		["desc"] = "Put together a SPAS-12",
		["requirements"] = {["advancedshotgunbody"] = 1, ["advancedsemi"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 30, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["spas12"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_saiga12"] = {
		["name"] = "Saiga-12",
		["model"] = "models/weapons/ethereal/w_saiga_12k.mdl",
		["desc"] = "Put together a Saiga-12",
		["requirements"] = {["advancedshotgunbody"] = 1, ["advancedsemi"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 35, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["saiga12"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_w9422"] = {
		["name"] = "Winchester 9422",
		["model"] = "models/weapons/tfa_nmrih/w_fa_win1892.mdl",
		["desc"] = "Put together a Winchester 9422",
		["requirements"] = {["basicriflebody"] = 1, ["basicsemi"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 10, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["w9422"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_trg42"] = {
		["name"] = "SAKO TRG-42",
		["model"] = "models/weapons/tgr/w_spin_scout.mdl",
		["desc"] = "Put together a SAKO TRG-42",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedsemi"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 45, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["trg42"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_toz34short"] = {
		["name"] = "TOZ-34 Sawnoff",
		["model"] = "models/weapons/w_sv10s.mdl",
		["desc"] = "Put together a TOZ-34 Sawnoff",
		["requirements"] = {["basicshotgunbody"] = 1, ["basicpump"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 8, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["toz34short"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_toz34"] = {
		["name"] = "TOZ-34",
		["model"] = "models/weapons/w_sv10.mdl",
		["desc"] = "Put together a TOZ-34",
		["requirements"] = {["basicshotgunbody"] = 1, ["basicpump"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 15, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["toz34"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_svt40"] = {
		["name"] = "SVT 40",
		["model"] = "models/weapons/w_svt40.mdl",
		["desc"] = "Put together a SVT 40",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedsemi"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 35, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["svt40"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_striker"] = {
		["name"] = "Striker",
		["model"] = "models/weapons/w_shot_strike.mdl",
		["desc"] = "Put together a Striker",
		["requirements"] = {["advancedshotgunbody"] = 1, ["advancedsemi"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 35, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["striker"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_sterling"] = {
		["name"] = "Sterling",
		["model"] = "models/weapons/b_sterling.mdl",
		["desc"] = "Put together a Sterling",
		["requirements"] = {["standardsmgbody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 18, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["sterling"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_sten"] = {
		["name"] = "Sten Gun MKII",
		["model"] = "models/weapons/w_smg_ste.mdl",
		["desc"] = "Put together a Sten Gun MKII",
		["requirements"] = {["standardsmgbody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 15, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["sten"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_stechaps"] = {
		["name"] = "Stechkin APS",
		["model"] = "models/weapons/w_ma85_wf_pt10.mdl",
		["desc"] = "Put together a Stechkin APS",
		["requirements"] = {["standardsmgbody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 15, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["stechaps"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_sr3m"] = {
		["name"] = "SR-3M Vikhr",
		["model"] = "models/weapons/w_dmg_vikhr.mdl",
		["desc"] = "Put together a SR-3M Vikhr",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 45, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["sr3m"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_skorpion"] = {
		["name"] = "Skorpion",
		["model"] = "models/weapons/w_smg_skorp.mdl",
		["desc"] = "Put together a Skorpion",
		["requirements"] = {["standardsmgbody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 14, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["skorpion"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_sako85"] = {
		["name"] = "Sako 85",
		["model"] = "models/weapons/tfa_nmrih/w_fa_sako85_ironsights.mdl",
		["desc"] = "Put together a Sako 85",
		["requirements"] = {["standardriflebody"] = 1, ["standardbolt"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 25, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["sako85"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_rugermk3"] = {
		["name"] = "Ruger MKIII",
		["model"] = "models/weapons/w_pist_ruger23a1.mdl",
		["desc"] = "Put together a Ruger MKIII",
		["requirements"] = {["basicpistolbody"] = 1, ["basicsemi"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 6, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["rugermk3"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_ruger1022"] = {
		["name"] = "Ruger 10/22",
		["model"] = "models/weapons/tfa_nmrih/w_fa_ruger1022.mdl",
		["desc"] = "Put together a Ruger 10/22",
		["requirements"] = {["basicriflebody"] = 1, ["basicsemi"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 10, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["ruger1022"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_rk95"] = {
		["name"] = "SAKO RK 95",
		["model"] = "models/weapons/world/rifles/rk95.mdl",
		["desc"] = "Put together a SAKO RK 95",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 35, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["rk95"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_rem870ae"] = {
		["name"] = "Remington 870 AE",
		["model"] = "models/weapons/w_shot_remington.mdl",
		["desc"] = "Put together a Remington 870 AE",
		["requirements"] = {["standardshotgunbody"] = 1, ["standardpump"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 20, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["rem870ae"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_ppsh"] = {
		["name"] = "PPSh-41",
		["model"] = "models/weapons/w_grub_ppsh_stick.mdl",
		["desc"] = "Put together a PPSh-41",
		["requirements"] = {["standardsmgbody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 24, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["ppsh"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_pp2000"] = {
		["name"] = "PP-2000",
		["model"] = "models/weapons/w_bf4_pp2000.mdl",
		["desc"] = "Put together a PP-2000",
		["requirements"] = {["basicsmgbody"] = 1, ["basicauto"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 7, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["pp2000"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_pp19"] = {
		["name"] = "PP-19 Bizon",
		["model"] = "models/weapons/w_smg_biz.mdl",
		["desc"] = "Put together a PP-19 Bizon",
		["requirements"] = {["standardsmgbody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 15, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["pp19"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_pkm"] = {
		["name"] = "PKM",
		["model"] = "models/weapons/w_mach_pkmbenis.mdl",
		["desc"] = "Put together a PKM",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 75, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["pkm"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_obrez"] = {
		["name"] = "Obrez",
		["model"] = "models/weapons/w_obrez.mdl",
		["desc"] = "Put together an Obrez",
		["requirements"] = {["basicriflebody"] = 1, ["basicbolt"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 14, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["obrez"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_mp9a1"] = {
		["name"] = "MP9a1",
		["model"] = "models/weapons/w_smg_mp9a1.mdl",
		["desc"] = "Put together a MP9a1",
		["requirements"] = {["basicsmgbody"] = 1, ["basicauto"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 12, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {[""] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_mossberg500"] = {
		["name"] = "Mossberg 500",
		["model"] = "models/weapons/w_shot_mossberg5.mdl",
		["desc"] = "Put together a Mossberg 500",
		["requirements"] = {["standardshotgunbody"] = 1, ["standardpump"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 18, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["mossberg500"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_mini14"] = {
		["name"] = "Mini-14",
		["model"] = "models/weapons/ethereal/w_mini14.mdl",
		["desc"] = "Put together a Mini-14",
		["requirements"] = {["standardriflebody"] = 1, ["standardsemi"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 22, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["mini14"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_mac11"] = {
		["name"] = "Mac-11",
		["model"] = "models/weapons/w_cst_mac11.mdl",
		["desc"] = "Put together a Mac-11",
		["requirements"] = {["basicsmgbody"] = 1, ["basicauto"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 11, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["mac11"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_m3super90"] = {
		["name"] = "M3 Super 90",
		["model"] = "models/weapons/w_cstm_m3super90.mdl",
		["desc"] = "Put together a M3 Super 90",
		["requirements"] = {["advancedshotgunbody"] = 1, ["advancedsemi"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 25, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {[""] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_m3supershort"] = {
		["name"] = "Serbu Super Shorty",
		["model"] = "models/weapons/w_shot_shortygun.mdl",
		["desc"] = "Put together a Serbu Super Shorty",
		["requirements"] = {["basicshotgunbody"] = 1, ["basicpump"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 12, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["m3supershort"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_kiparis"] = {
		["name"] = "OTs-02 Kiparis",
		["model"] = "models/weapons/w_smg_skorp.mdl",
		["desc"] = "Put together a OTs-02 Kiparis",
		["requirements"] = {["standardsmgbody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 17, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["kiparis"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_fort12"] = {
		["name"] = "Fort-12",
		["model"] = "models/srp/weapons/w_fort12.mdl",
		["desc"] = "Put together a Fort-12",
		["requirements"] = {["basicpistolbody"] = 1, ["basicsemi"] = 1, ["basicinternals"] = 1, ["scrapmetal"] = 7, ["smallgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["fort12"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_cz52"] = {
		["name"] = "CZ-52",
		["model"] = "models/weapons/w_pist_cz52.mdl",
		["desc"] = "Put together a CZ-52",
		["requirements"] = {["standardpistolbody"] = 1, ["standardsemi"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 14, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["cz52"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_brhp"] = {
		["name"] = "Browning Hi-Power",
		["model"] = "models/weapons/w_pist_brhp.mdl",
		["desc"] = "Put together a Browning Hi-Power",
		["requirements"] = {["standardpistolbody"] = 1, ["standardsemi"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 11, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["brhp"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_anaconda"] = {
		["name"] = "Colt Anaconda",
		["model"] = "models/weapons/w_python.mdl",
		["desc"] = "Put together a Colt Anaconda",
		["requirements"] = {["advancedpistolbody"] = 1, ["advancedsemi"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 20, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["anaconda"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	/*
	["guns_l115"] = {
		["name"] = "L115",
		["model"] = "models/weapons/w_cstm_l96.mdl",
		["desc"] = "Put together a L115",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedsemi"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 50, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["l115"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_dp28"] = {
		["name"] = "DP-28",
		["model"] = "models/weapons/w_ro2_dp28.mdl",
		["desc"] = "Put together a DP-28",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 55, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["dp28"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_rpk"] = {
		["name"] = "RPK",
		["model"] = "models/weapons/ethereal/w_rpk.mdl",
		["desc"] = "Put together a RPK",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 45, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["rpk"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_rpk74m"] = {
		["name"] = "RPK-74M",
		["model"] = "models/weapons/ethereal/w_f_rpk74m.mdl",
		["desc"] = "Put together a RPK-74M",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 50, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["rpk74m"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_br99"] = {
		["name"] = "BR-99",
		["model"] = "models/weapons/ethereal/w_br99.mdl",
		["desc"] = "Put together a BR-99",
		["requirements"] = {["advancedshotgunbody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 45, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["br99"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_mp7"] = {
		["name"] = "MP7",
		["model"] = "models/weapons/ethereal/w_mp7.mdl",
		["desc"] = "Put together a MP7",
		["requirements"] = {["advancedsmgbody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 15, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["mp7"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_p90"] = {
		["name"] = "P90",
		["model"] = "models/weapons/ethereal/w_p90.mdl",
		["desc"] = "Put together a P90",
		["requirements"] = {["advancedsmgbody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 20, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["p90"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_m14wood"] = {
		["name"] = "Wood M14",
		["model"] = "models/weapons/ethereal/w_m14_wood.mdl",
		["desc"] = "Put together a Wood Furniture M14",
		["requirements"] = {["standardriflebody"] = 1, ["standardauto"] = 1, ["standardinternals"] = 1, ["scrapmetal"] = 25, ["mediumgunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["m14wood"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_m14ebr"] = {
		["name"] = "M14 EBR",
		["model"] = "models/weapons/ethereal/w_m14.mdl",
		["desc"] = "Put together a M14 EBR",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 45, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["m14"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_scarh"] = {
		["name"] = "SCAR-H",
		["model"] = "models/weapons/ethereal/w_sca.mdl",
		["desc"] = "Put together a SCAR-H",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedsemi"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 50, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["scarh"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_svu"] = {
		["name"] = "SVU",
		["model"] = "models/weapons/ethereal/w_svu.mdl",
		["desc"] = "Put together a SVU",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedsemi"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 50, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["svu"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_ks23"] = {
		["name"] = "KS-23",
		["model"] = "models/weapons/ethereal/w_ks23.mdl",
		["desc"] = "Put together a BR-99",
		["requirements"] = {["advancedshotgunbody"] = 1, ["advancedpump"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 45, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["ks23"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_rpk12"] = {
		["name"] = "RPK-12",
		["model"] = "models/weapons/ethereal/w_rpk12.mdl",
		["desc"] = "Put together a RPK-12",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 65, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["rpk12"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "A",
	},
	["guns_m249"] = {
		["name"] = "M249",
		["model"] = "models/weapons/ethereal/w_m249.mdl",
		["desc"] = "Put together a M249",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 70, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["m249"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "A",
	},
	["guns_m240"] = {
		["name"] = "M240",
		["model"] = "models/weapons/ethereal/w_m240.mdl",
		["desc"] = "Put together a M249",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 75, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["m240"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "A",
	},
	["guns_pkp"] = {
		["name"] = "PKP Pecheneg",
		["model"] = "models/weapons/ethereal/w_pkp.mdl",
		["desc"] = "Put together a PKP Pecheneg",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 75, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["pkp"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "A",
	},
	["guns_ak12u"] = {
		["name"] = "AK-12u",
		["model"] = "models/weapons/ethereal/w_ak12u.mdl",
		["desc"] = "Put together an AK-12u",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 35, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["ak12u"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["guns_ak12"] = {
		["name"] = "AK-12",
		["model"] = "models/weapons/ethereal/w_ak12.mdl",
		["desc"] = "Put together an AK-12",
		["requirements"] = {["advancedriflebody"] = 1, ["advancedauto"] = 1, ["advancedinternals"] = 1, ["scrapmetal"] = 45, ["largegunoil"] = 1, ["gunsmithtools"] = 1},
		["results"] = {["ak12"] = 1},
		["category"] = "Gunsmithing",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	*/
}

for k, v in pairs(NEW_RECIPES) do
	PLUGIN:AddRecipe(v.name, v.model, v.desc, v.requirements, v.results, k, v.skill or nil, v.blueprint or nil, v.guns or nil, v.entity or nil, v.category or "Miscellaneous", v.crafttable or nil)
end