local NEW_RECIPES = {
	-- 		SCRAP/JUNK
	["scrap_pot"] = {
		["name"] = "Pot",
		["model"] = "models/props_interiors/pot02a.mdl",
		["desc"] = "Break down this pot to get some scrap.",
		["requirements"] = {["pot"] = 1},
		["results"] = {["scrapmetal"] = 3},
		["category"] = "Scrap",
		["crafttable"] = "scraptable",
	},
	["scrap_metalgascan"] = {
		["name"] = "Metal Gas Can",
		["model"] = "models/props_junk/metalgascan.mdl",
		["desc"] = "Break down this metal gas can to get some scrap.",
		["requirements"] = {["metalgascan"] = 1},
		["results"] = {["scrapmetal"] = 6},
		["category"] = "Scrap",
		["crafttable"] = "scraptable",
	},
	["scrap_laptop"] = {
		["name"] = "Laptop",
		["model"] = "models/kek1ch/notebook.mdl",
		["desc"] = "Break down this laptop to get some scrap.",
		["requirements"] = {["laptop"] = 1},
		["results"] = {["scrapmetal"] = 2, ["wire"] = 2, ["electronics"] = 2},
		["category"] = "Scrap",
		["crafttable"] = "scraptable",
	},
	["scrap_ipod"] = {
		["name"] = "MP3 Player",
		["model"] = "models/kek1ch/iped.mdl",
		["desc"] = "Break down this MP3 Player to get some scrap.",
		["requirements"] = {["ipod"] = 1},
		["results"] = {["scrapmetal"] = 1, ["wire"] = 1, ["electronics"] = 1},
		["category"] = "Scrap",
		["crafttable"] = "scraptable",
	},
	["scrap_iphone"] = {
		["name"] = "Smartphone",
		["model"] = "models/kek1ch/iphone.mdl",
		["desc"] = "Break down this Smartphone to get some scrap.",
		["requirements"] = {["iphone"] = 1},
		["results"] = {["scrapmetal"] = 1, ["wire"] = 1, ["electronics"] = 2},
		["category"] = "Scrap",
		["crafttable"] = "scraptable",
	},
	["scrap_emptycan"] = {
		["name"] = "Empty Can",
		["model"] = "models/props_junk/garbage_metalcan002a.mdl",
		["desc"] = "Break down this empty can to get some scrap.",
		["requirements"] = {["emptycan"] = 1},
		["results"] = {["scrapmetal"] = 1},
		["category"] = "Scrap",
		["crafttable"] = "scraptable",
	},
	["scrap_cassetteplayer"] = {
		["name"] = "Cassette Player",
		["model"] = "models/kek1ch/portable_player.mdl",
		["desc"] = "Break down this cassette player to get some scrap.",
		["requirements"] = {["cassetteplayer"] = 1},
		["results"] = {["electronics"] = 1, ["wire"] = 2},
		["category"] = "Scrap",
		["crafttable"] = "scraptable",
	},
	["scrap_bucket"] = {
		["name"] = "Bucket",
		["model"] = "models/props_junk/metalbucket01a.mdl",
		["desc"] = "Break down this bucket to get some scrap.",
		["requirements"] = {["bucket"] = 1},
		["results"] = {["scrapmetal"] = 3},
		["category"] = "Scrap",
		["crafttable"] = "scraptable",
	},
	["scrap_brokenradio"] = {
		["name"] = "Broken Radio",
		["model"] = "models/props/cs_office/radio.mdl",
		["desc"] = "Break down this radio to get some scrap.",
		["requirements"] = {["brokenradio"] = 1},
		["results"] = {["electronics"] = 1, ["wire"] = 2},
		["category"] = "Scrap",
		["crafttable"] = "scraptable",
	},
	-- 		NORMAL AMMO
	["scrap_9x18"] = {
		["name"] = "9x19mm",
		["model"] = "models/kek1ch/ammo_9x19_fmj.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["9x18"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 1, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_9x19"] = {
		["name"] = "9x19mm",
		["model"] = "models/kek1ch/ammo_9x19_fmj.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["9x19"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 1, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_9x21"] = {
		["name"] = "9x21mm",
		["model"] = "models/kek1ch/ammo_9x19_pbp.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["9x21"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 1, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_38"] = {
		["name"] = ".38 Special",
		["model"] = "models/Items/357ammo.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["38"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 1, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_762x25"] = {
		["name"] = "7.62x25mm",
		["model"] = "models/kek1ch/ammo_762x25_p.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["762x25"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 1, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_57"] = {
		["name"] = "5.7x28mm",
		["model"] = "models/kek1ch/ammo_762x25_ps.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["57x28"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 1, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_45"] = {
		["name"] = ".45 ACP",
		["model"] = "models/kek1ch/ammo_1143x23_fmj.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["45acp"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 2, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_357"] = {
		["name"] = ".357 Magnum",
		["model"] = "models/Items/357ammo.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["357"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 2, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_50"] = {
		["name"] = ".50 AE",
		["model"] = "models/kek1ch/ammo_50_ae.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["50ae"] = 100},
		["results"] = {["gunpowder"] = 2, ["scrapmetal"] = 3, ["brass"] = 2},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_12x70birdshot"] = {
		["name"] = "12 Gauge Birdshot",
		["model"] = "models/kek1ch/ammo_12x70_buck.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["12gaugebd"] = 100},
		["results"] = {["gunpowder"] = 2, ["scrapmetal"] = 3, ["brass"] = 2},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_12x70"] = {
		["name"] = "12 Gauge Buckshot",
		["model"] = "models/kek1ch/ammo_12x70_buck.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["12gauge"] = 100},
		["results"] = {["gunpowder"] = 2, ["scrapmetal"] = 3, ["brass"] = 2},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_12x70slug"] = {
		["name"] = "12 Gauge Slug",
		["model"] = "models/kek1ch/ammo_12x70_buck.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["12gaugesg"] = 100},
		["results"] = {["gunpowder"] = 3, ["scrapmetal"] = 4, ["brass"] = 3},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_12x70trishot"] = {
		["name"] = "12 Gauge Trishot",
		["model"] = "models/kek1ch/ammo_12x70_buck.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["12gaugetr"] = 100},
		["results"] = {["gunpowder"] = 2, ["scrapmetal"] = 3, ["brass"] = 2},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_762x39"] = {
		["name"] = "7.62x39mm",
		["model"] = "models/kek1ch/ammo_762x39_ap.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["762x39"] = 100},
		["results"] = {["gunpowder"] = 2, ["scrapmetal"] = 3, ["brass"] = 2},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_545x39"] = {
		["name"] = "5.45x39mm",
		["model"] = "models/kek1ch/ammo_545x39_fmj.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["545x39"] = 100},
		["results"] = {["gunpowder"] = 2, ["scrapmetal"] = 3, ["brass"] = 2},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_556x45"] = {
		["name"] = "5.56x45mm",
		["model"] = "models/kek1ch/ammo_556x45_ss190.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["556x45"] = 100},
		["results"] = {["gunpowder"] = 2, ["scrapmetal"] = 3, ["brass"] = 2},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_9x39"] = {
		["name"] = "9x39mm",
		["model"] = "models/kek1ch/ammo_9x39_pab9.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["9x39"] = 100},
		["results"] = {["gunpowder"] = 3, ["scrapmetal"] = 4, ["brass"] = 3},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_762x51"] = {
		["name"] = "7.62x51mm",
		["model"] = "models/kek1ch/ammo_762x54_7h14.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["762x51"] = 100},
		["results"] = {["gunpowder"] = 3, ["scrapmetal"] = 4, ["brass"] = 3},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_762x54"] = {
		["name"] = "7.62x54mmR",
		["model"] = "models/kek1ch/ammo_762x54_7h1.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["762x54"] = 100},
		["results"] = {["gunpowder"] = 3, ["scrapmetal"] = 4, ["brass"] = 3},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_23"] = {
		["name"] = "23mm Buckshot",
		["model"] = "models/kek1ch/ammo_12x76_zhekan.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["23"] = 50},
		["results"] = {["gunpowder"] = 4, ["scrapmetal"] = 6, ["brass"] = 4},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_762x51belt"] = {
		["name"] = "7.62x51mm Belt",
		["model"] = "models/kek1ch/ammo_pkm.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["762x51belt"] = 100},
		["results"] = {["gunpowder"] = 8, ["scrapmetal"] = 11, ["brass"] = 8},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_762x54belt"] = {
		["name"] = "7.62x54mm Belt",
		["model"] = "models/kek1ch/ammo_pkm.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["762x54belt"] = 100},
		["results"] = {["gunpowder"] = 8, ["scrapmetal"] = 11, ["brass"] = 8},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_molotov"] = {
		["name"] = "Molotov Cocktail",
		["model"] = "models/weapons/ethereal/w_molotov.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["molotov"] = 1},
		["results"] = {["alcohol"] = 1, ["cloth"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	-- 		ZONE LOADED AMMO
	["scrap_9x18zl"] = {
		["name"] = "9x18mm ZL",
		["model"] = "models/kek1ch/ammo_9x19_fmj.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["9x18zl"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 1, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_9x19zl"] = {
		["name"] = "9x19mm ZL",
		["model"] = "models/kek1ch/ammo_9x19_fmj.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["9x19zl"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 1, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_762x25zl"] = {
		["name"] = "7.62x25mm ZL",
		["model"] = "models/kek1ch/ammo_762x25_p.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["762x25zl"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 1, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_57zl"] = {
		["name"] = "5.7x28mm ZL",
		["model"] = "models/kek1ch/ammo_762x25_ps.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["57x28zl"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 1, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_45zl"] = {
		["name"] = ".45 ACP ZL",
		["model"] = "models/kek1ch/ammo_1143x23_fmj.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["45acpzl"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 1, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_50zl"] = {
		["name"] = ".50 AE ZL",
		["model"] = "models/kek1ch/ammo_50_ae.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["50aezl"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 2, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_12x70zl"] = {
		["name"] = "12 Gauge Buckshot ZL",
		["model"] = "models/kek1ch/ammo_12x70_buck.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["12gaugezl"] = 50},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 2, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_762x39zl"] = {
		["name"] = "7.62x39mm ZL",
		["model"] = "models/kek1ch/ammo_762x39_ap.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["762x39zl"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 2, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_545x39zl"] = {
		["name"] = "5.45x39mm ZL",
		["model"] = "models/kek1ch/ammo_545x39_fmj.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["545x39zl"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 2, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_556x45zl"] = {
		["name"] = "5.56x45mm ZL",
		["model"] = "models/kek1ch/ammo_556x45_ss190.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["556x45zl"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 2, ["brass"] = 1},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_9x39zl"] = {
		["name"] = "9x39mm ZL",
		["model"] = "models/kek1ch/ammo_9x39_pab9.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["9x39zl"] = 100},
		["results"] = {["gunpowder"] = 1, ["scrapmetal"] = 3, ["brass"] = 2},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_762x51zl"] = {
		["name"] = "7.62x51mm ZL",
		["model"] = "models/kek1ch/ammo_762x54_7h14.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["762x51zl"] = 100},
		["results"] = {["gunpowder"] = 2, ["scrapmetal"] = 3, ["brass"] = 2},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
	["scrap_762x54zl"] = {
		["name"] = "7.62x54mmR ZL",
		["model"] = "models/kek1ch/ammo_762x54_7h1.mdl",
		["desc"] = "Reclaim ",
		["requirements"] = {["762x54zl"] = 100},
		["results"] = {["gunpowder"] = 2, ["scrapmetal"] = 3, ["brass"] = 2},
		["category"] = "Scrap: Ammo",
		["crafttable"] = "gunsmithing",
		["flag"] = "2",
	},
}

for k, v in pairs(NEW_RECIPES) do
	PLUGIN:AddRecipe(v.name, v.model, v.desc, v.requirements, v.results, k, v.skill or nil, v.blueprint or nil, v.guns or nil, v.entity or nil, v.category or "Miscellaneous", v.crafttable or nil)
end