ITEM.name = "Alcohol"
ITEM.model = ("models/kek1ch/dev_vodka2.mdl")
ITEM.description = "A bit of alcohol, you're not entirely sure what kind. You could drink it, or you could use it as a subpar molotov cocktail."
ITEM.price = 500
ITEM.flag = "a"
ITEM.category = "Misc"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 50
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.1