ITEM.name = "Advanced Automatic Receiver"
ITEM.model = ("models/kek1ch/toolkit_r.mdl")
ITEM.description = "An exotic automatic receiver."
ITEM.price = 500
ITEM.flag = "a"
ITEM.category = "Misc"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 5
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.5
ITEM.color = Color(76,0,176)