ITEM.name = "Brass"
ITEM.model = ("models/props/cs_militia/reload_bullet_tray.mdl")
ITEM.description = "A small box of assorted brass casings, some used, some not."
ITEM.price = 500
ITEM.flag = "a"
ITEM.category = "Misc"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 50
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.1