ITEM.name = "Basic Bolt-Action"
ITEM.model = ("models/kek1ch/toolkit_p.mdl")
ITEM.description = "A simple bolt-action."
ITEM.price = 500
ITEM.flag = "a"
ITEM.category = "Misc"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 5
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.5
ITEM.color = Color(12,176,0)