ITEM.name = "Cassette Player"
ITEM.model = ("models/kek1ch/portable_player.mdl")
ITEM.description = "A cassette player, from the days of old. Where'd you even find something this old?"
ITEM.price = 500
ITEM.flag = "a"
ITEM.category = "Misc"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 5
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.1