ITEM.name = "Empty Can"
ITEM.model = ("models/props_junk/garbage_metalcan002a.mdl")
ITEM.description = "An empty metal can."
ITEM.price = 500
ITEM.flag = "a"
ITEM.category = "Misc"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 10
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.1