ITEM.name = "Gunpowder"
ITEM.model = ("models/props_lab/jar01b.mdl")
ITEM.description = "A rather small amount of gunpowder in a rather large jar."
ITEM.price = 500
ITEM.flag = "a"
ITEM.category = "Misc"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 50
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.1