ITEM.name = "Glue"
ITEM.model = ("models/kek1ch/glue_e.mdl")
ITEM.description = "Glue, for holding things together, much like tape, but not."
ITEM.price = 500
ITEM.flag = "a"
ITEM.category = "Misc"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 50
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.1