ITEM.name = "MP3 Player"
ITEM.model = ("models/kek1ch/iped.mdl")
ITEM.description = "A simple MP3 Player, less common than smartphones, but with more generally large enough to be useful components inside."
ITEM.price = 500
ITEM.flag = "a"
ITEM.category = "Misc"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 5
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.45