ITEM.name = "Scrap Metal"
ITEM.model = ("models/props_debris/metal_panelshard01c.mdl")
ITEM.description = "A relatively small piece of metal. Useful for various applications."
ITEM.price = 50
ITEM.flag = "a"
ITEM.category = "Misc"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 100
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.1