ITEM.name = "Standard SMG Body"
ITEM.model = ("models/kek1ch/safe_container.mdl")
ITEM.description = "The body of a rather average SMG."
ITEM.price = 500
ITEM.flag = "a"
ITEM.category = "Misc"
ITEM.basequantity = 1
ITEM.quantity = 1
ITEM.maxQuantity = 5
ITEM.isStackable = false
ITEM.canSplit = true
ITEM.weight = 0.5
ITEM.color = Color(0,44,176)