ITEM.name = "Winter IO8A"
ITEM.description = "A basic IO8A suit designed for cold environments."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/io7a.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 8
ITEM.replacements = "models/tnb/stalker/male_io8a.mdl"