ITEM.name = "Iron Wolves Sunrise"
ITEM.description = "A basic Sunrise suit colored in favor of the Iron Wolves."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/sunrise.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 7
ITEM.replacements = {"anorak", "sunrise"}