ITEM.name = "PSZ-9Md"
ITEM.description = "A custom Seva suit designed for Duty."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/seva.mdl"
ITEM.width = 2
ITEM.height = 3
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 1
ITEM.replacements = "models/tnb/stalker/male_seva.mdl"