ITEM.name = "PSZ-9d"
ITEM.description = "A custom SKAT suit designed for Duty."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/skat.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 1
ITEM.replacements = "models/tnb/stalker/male_skat.mdl"