ITEM.name = "Standard CS3"
ITEM.description = "A basic CS3 suit."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/io7a.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 0
ITEM.replacements = "models/tnb/stalker/male_cs3_mask.mdl"