ITEM.name = "Black CS2"
ITEM.description = "A basic CS2 suit colored black."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/io7a.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 1
ITEM.replacements = "models/tnb/stalker/male_cs2.mdl"