ITEM.name = "Olive Exoskeleton"
ITEM.description = "A basic Exoskeleton colored in olive."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/exo.mdl"
ITEM.width = 2
ITEM.height = 3
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 7
ITEM.replacements = "models/tnb/stalker/male_exo.mdl"