ITEM.name = "Winter IO7A"
ITEM.description = "A basic IO7A suit designed for cold environments."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/io7a.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 8
ITEM.replacements = "models/tnb/stalker/male_io7a.mdl"