ITEM.name = "Military SKAT-9M Exoskeleton"
ITEM.description = "A basic SKAT-9M Exoskeleton colored in favor of Ukranian Military."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/exo.mdl"
ITEM.width = 2
ITEM.height = 3
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 4
ITEM.replacements = "models/tnb/stalker/male_skat_exo.mdl"