ITEM.name = "Olive-Green Sunrise"
ITEM.description = "A basic Sunrise suit colored olive-green."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/sunrise.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 9
ITEM.replacements = {"anorak", "sunrise"}