ITEM.name = "Forest Sunrise"
ITEM.description = "A basic Sunrise suit colored for the forest."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/sunrise.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 8
ITEM.replacements = {"anorak", "sunrise"}