ITEM.name = "Standard SKAT-9M"
ITEM.description = "A basic SKAT-9M suit."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/skat.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 0
ITEM.replacements = "models/tnb/stalker/male_skat.mdl"