ITEM.name = "Floral Seva"
ITEM.description = "A basic Seva suit colored floral."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/seva.mdl"
ITEM.width = 2
ITEM.height = 3
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 9
ITEM.replacements = "models/tnb/stalker/male_seva.mdl"