ITEM.name = "Brown Flannel Anorak"
ITEM.description = "A brown flannel Anorak."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/anorak.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 7
