ITEM.name = "Black Berill"
ITEM.description = "A basic Berill suit colored black."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/berill.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 1
ITEM.replacements = "models/tnb/stalker/male_berill.mdl"