ITEM.name = "Berill-5m"
ITEM.description = "A custom Berill suit designed for the Ukranian Military."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/berill.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 0
ITEM.replacements = "models/tnb/stalker/male_berill.mdl"