ITEM.name = "Standard Exoskeleton"
ITEM.description = "A basic Exoskeleton."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/exo.mdl"
ITEM.width = 2
ITEM.height = 3
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 0
ITEM.replacements = "models/tnb/stalker/male_exo.mdl"