ITEM.name = "Freedom Exoskeleton"
ITEM.description = "A custom Exoskeleton designed by Freedom."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/exo.mdl"
ITEM.width = 2
ITEM.height = 3
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 2
ITEM.replacements = "models/tnb/stalker/male_exo.mdl"