ITEM.name = "Standard Seva"
ITEM.description = "A basic Seva suit."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/seva.mdl"
ITEM.width = 2
ITEM.height = 3
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 0
ITEM.replacements = "models/tnb/stalker/male_seva.mdl"