ITEM.name = "Wind of Freedom"
ITEM.description = "A custom Sunrise suit designed for Freedom."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/sunrise.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 2
ITEM.replacements = {"anorak", "sunrise"}