ITEM.name = "PSZ-9a"
ITEM.description = "A custom Sunrise suit designed by Duty."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/sunrise.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 1
ITEM.replacements = {"anorak", "sunrise"}