ITEM.name = "Black SKAT-9M"
ITEM.description = "A basic SKAT-9M suit colored in black."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/skat.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 4
ITEM.replacements = "models/tnb/stalker/male_skat.mdl"