ITEM.name = "Clear Sky Sunrise"
ITEM.description = "A basic Sunrise suit colored in favor of Clear Sky."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/sunrise.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 10
ITEM.replacements = {"anorak", "sunrise"}