ITEM.name = "Dark Green Sunrise"
ITEM.description = "A basic Sunrise suit colored dark green."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/sunrise.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 11
ITEM.replacements = {"anorak", "sunrise"}