ITEM.name = "Dark Camo Sunrise"
ITEM.description = "A basic Sunrise suit colored in dark camo."
ITEM.category = "Outfit"
ITEM.model = "models/tnb/stalker/items/sunrise.mdl"
ITEM.width = 2
ITEM.height = 2
ITEM.outfitCategory = "model"
ITEM.pacData = {}
ITEM.newSkin = 6
ITEM.replacements = {"anorak", "sunrise"}