ITEM.name = "Large Cleaning Kit"
ITEM.description = "A large cleaning kit, for cleaning a weapon after use."
ITEM.category = "Repair"
ITEM.model = "models/kek1ch/cleaning_kit_r7.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 800
ITEM.busflag = {"technician1_1_1"}
ITEM.weight = 0.8
ITEM.repair = 20