ITEM.name = "Large Gun Oil"
ITEM.description = "A large container of gun oil, for lubricating a weapon after use."
ITEM.category = "Repair"
ITEM.model = "models/kek1ch/gun_oil.mdl"
ITEM.width = 1
ITEM.height = 2
ITEM.price = 800
ITEM.busflag = {"technician1_1_1"}
ITEM.weight = 0.5
ITEM.repair = 10