ITEM.name = "Medium Cleaning Kit"
ITEM.description = "A medium sized cleaning kit, for cleaning a weapon after use."
ITEM.category = "Repair"
ITEM.model = "models/kek1ch/cleaning_kit_r5.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 800
ITEM.busflag = {"technician1_1"}
ITEM.weight = 0.5
ITEM.repair = 10