ITEM.name = "Small Gun Oil"
ITEM.description = "A small container of gun oil, for lubricating a weapon after use."
ITEM.category = "Repair"
ITEM.model = "models/kek1ch/gun_oil_ru_d.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 800
ITEM.busflag = {"technician1"}
ITEM.weight = 0.2
ITEM.repair = 2.5