ITEM.name = "Small Cleaning Kit"
ITEM.description = "A small on-the-go cleaning kit, for cleaning a weapon after use."
ITEM.category = "Repair"
ITEM.model = "models/kek1ch/cleaning_kit_p.mdl"
ITEM.width = 1
ITEM.height = 1
ITEM.price = 800
ITEM.busflag = {"technician1"}
ITEM.weight = 0.35
ITEM.repair = 5