ITEM.name = "Bubble";
ITEM.description = "Emits a passive, gaseous substance that neutralizes radioactive particles inside the body. Side Effects: Causes continual buildup of gaseous activity within the body, thus causing occasional flatulence and belching. [-6 rad]";
ITEM.category = "Artifacts";
ITEM.model = "models/tnb/stalker/artifacts/bubble.mdl";
ITEM.width = 1;
ITEM.height = 1;
ITEM.weight = 1;
ITEM.isArtefact = true;
ITEM.price = 17350
ITEM.flag = "Z"
ITEM.buff = "antirad"
ITEM.buffval = 6
ITEM.weight = 1.85