ITEM.name = "Battery";
ITEM.description = "Stimulates the production of ATP in human cells, reducing fatigue and giving a decent boost to stamina recovery. Emits a moderate amount of radiation. Causes short term insomnia. [+2/+2 rad]";
ITEM.category = "Artifacts";
ITEM.model = "models/tnb/stalker/artifacts/battery.mdl";
ITEM.width = 1;
ITEM.height = 1;
ITEM.weight = 1;
ITEM.isArtefact = true;
ITEM.price = 820
ITEM.flag = "Z"
ITEM.buff = "end"
ITEM.buffval = 2
ITEM.debuff = "rads"
ITEM.debuffval = 2
ITEM.weight = 0.75