ITEM.name = "Crystal";
ITEM.description = "Emits a minor amount of radiation and actively consumes nearby excess heat. Maintains an internal temperature, providing a small amount of warmth under 15 Celsius.. [+1/+1 rad]";
ITEM.category = "Artifacts";
ITEM.model = "models/nasca/etherealsrp_artifacts/crystal.mdl";
ITEM.width = 1;
ITEM.height = 1;
ITEM.weight = 1;
ITEM.isArtefact = true;
ITEM.price = 1120
ITEM.flag = "Z"
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.weight = 2.35