ITEM.name = "Dreamcatcher";
ITEM.description = "Stalkers claim that whenever they have it with them, they don’t have nightmares and often experience a good night’s sleep. It emits no radiation. On the negative side, it makes Stalkers oversleep, which in turn makes them rather groggy early on in their day.";
ITEM.category = "Artifacts";
ITEM.model = "models/artefacts/black_angel.mdl";
ITEM.width = 1;
ITEM.height = 1;
ITEM.weight = 1;
ITEM.isArtefact = true;
ITEM.price = 520
ITEM.flag = "Z"
ITEM.weight = 0.5