ITEM.name = "Flame";
ITEM.description = "Speeds up the metabolic process similar to the Eye, quickly restoring damaged tissue. Emits a dangerous amount of radiation. Side Effect: Skin becomes sensitive. Regulates heat. [+6 Bleed/+3 rad]";
ITEM.category = "Artifacts";
ITEM.model = "models/tnb/stalker/artifacts/flame.mdl";
ITEM.width = 1;
ITEM.height = 1;
ITEM.weight = 1;
ITEM.isArtefact = true;
ITEM.price = 16485
ITEM.flag = "Z"
ITEM.buff = "woundheal"
ITEM.buffval = 6
ITEM.debuff = "rads"
ITEM.debuffval = 3
ITEM.weight = 1.2