ITEM.name = "Fireball";
ITEM.description = "Consumes excess heat in its surroundings, converting the energy into a minor amount of ionizing radiation. Maintains a constant temperature of 23° Celsius / 75° Fahrenheit. [+3 Heat/+1 rad]";
ITEM.category = "Artifacts";
ITEM.model = "models/nasca/etherealsrp_artifacts/fireball.mdl";
ITEM.width = 1;
ITEM.height = 1;
ITEM.weight = 1;
ITEM.isArtefact = true;
ITEM.price = 3595
ITEM.flag = "Z"
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.weight = 2.25