ITEM.name = "Flash";
ITEM.description = "Emits a minor amount of radiation and provides moderate protection against electric energy. Moderate increase of constant static electricity generated from the user. [+3/+1 rad]";
ITEM.category = "Artifacts";
ITEM.model = "models/tnb/stalker/artifacts/flash.mdl";
ITEM.width = 1;
ITEM.height = 1;
ITEM.weight = 1;
ITEM.isArtefact = true;
ITEM.price = 1940
ITEM.flag = "Z"
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.weight = 1.25