ITEM.name = "Firefly";
ITEM.description = "Considerably speeds up regeneration of tissue and organs in living beings, as well as normalizing metabolic processes. Cannot regrow or accelerate healing of bones. [+6 Healing/+4 rad]";
ITEM.category = "Artifacts";
ITEM.model = "models/tnb/stalker/artifacts/firefly.mdl";
ITEM.width = 1;
ITEM.height = 1;
ITEM.weight = 1;
ITEM.isArtefact = true;
ITEM.price = 20000
ITEM.flag = "Z"
ITEM.buff = "heal"
ITEM.buffval = 6
ITEM.debuff = "rads"
ITEM.debuffval = 4
ITEM.weight = 2.5