ITEM.name = "Meat Chunk";
ITEM.description = "Emits a minor amount of radiation and provides a moderate amount of protection against caustics. Increased production of mucus from nostrils. [+3 Chem/+1 rad]";
ITEM.category = "Artifacts";
ITEM.model = "models/srp/items/art_meatchunk.mdl";
ITEM.width = 1;
ITEM.height = 1;
ITEM.weight = 1;
ITEM.isArtefact = true;
ITEM.price = 2680
ITEM.flag = "Z"
ITEM.debuff = "rads"
ITEM.debuffval = 1
ITEM.weight = 1.35