ITEM.name = "Wrenched";
ITEM.description = "Acts as a sponge that absorbs nearby radiation. Slightly weaker than the Bubble. [-4]";
ITEM.category = "Artifacts";
ITEM.model = "models/nasca/etherealsrp_artifacts/slime.mdl";
ITEM.width = 1;
ITEM.height = 1;
ITEM.weight = 1;
ITEM.isArtefact = true;
ITEM.price = 10250
ITEM.flag = "Z"
ITEM.buff = "antirad"
ITEM.buffval = 4
ITEM.weight = 0.75